export const characteristicsMap: Record<string, string> = {
  "Effect Monster": "Monstro de efeito",
  "Flip Effect Monster": "Monstro de efeito",
  "Flip Tuner Effect Monster": "Monstro de efeito regulador",
  "Gemini Monster": "Monstro gêmeos",
  "Normal Monster": "Monstro normal",
  "Normal Tuner Monster": "Monstro normal regulador",
  "Pendulum Effect Monster": "Monstro de efeito pêndulo",
  "Pendulum Effect Ritual Monster": "Monstro de efeito pêndulo ritual",
  "Pendulum Flip Effect Monster": "Monstro de efeito pêndulo",
  "Pendulum Normal Monster": "Monstro normal pêndulo",
  "Pendulum Tuner Effect Monster": "Monstro de efeito regulador pêndulo",
  "Ritual Effect Monster": "Monstro de efeito ritual",
  "Ritual Monster": "Monstro ritual",
  "Spell Card": "Carta de magia",
  "spell": "Carta de magia",
  "Spirit Monster": "Monstro espírito",
  "Toon Monster": "Monstro toon",
  "Trap Card": "Carta de armadilha",
  "trap": "Carta de armadilha",
  "Tuner Monster": "Monstro regulador",
  "Union Effect Monster": "Monstro de efeito união",
  "Link Monster": "Monstro link",
  "Fusion Monster": "Monstro fusão",
  "Synchro Monster": "Monstro sincro",
  "Synchro Tuner Monster": "Monstro sincro regulador",
  "XYZ Monster": "Monstro xyz",
  "Skill Card": "Carta de habilidade",
  "Synchro Pendulum Effect Monster": "Monstro de efeito sincro pêndulo",
  "XYZ Pendulum Effect Monster": "Monstro de efeito xyz pêndulo",
  "Pendulum Effect Fusion Monster": "Monstro de efeito fusão pêndulo",
  "Token": "Ficha",
};

export const cardTypeMap: Record<string, string> = {
  Aqua: "Aqua",
  Beast: "Besta",
  "Beast-Warrior": "Besta guerreira",
  "Creator-God": "Deus criador",
  Cyberse: "Ciberso",
  Dinosaur: "Dinossauro",
  "Divine-Beast": "Besta divina",
  Dragon: "Dragão",
  Fairy: "Fada",
  Fiend: "Demônio",
  Fish: "Peixe",
  Insect: "Inseto",
  Machine: "Maquina",
  Plant: "Planta",
  Psychic: "Psíquico",
  Pyro: "Piro",
  Reptile: "Réptio",
  Rock: "Rocha",
  "Sea Serpent": "Serpente marinha",
  Spellcaster: "Mago",
  Thunder: "Trovão",
  Warrior: "Guerreiro",
  "Winged Beast": "Besta alada",
  Wyrm: "Wyrm",
  Zombie: "Zumbi",
  Normal: "Normal",
  Field: "Campo",
  Equip: "Equipamento",
  Continuous: "Continua",
  "Quick-Play": "Efeito rápido",
  Ritual: "Ritual",
  Counter: "Resposta",
};

export const cardAttributeMap: Record<string, string> = {
  DARK: "Trevas",
  LIGHT: "Luz",
  FIRE: "Fogo",
  WATER: "Água",
  WIND: "Vento",
  EARTH: "Terra",
  DIVINE: "Divino",
  SPELL: "Magia",
  TRAP: "Armadilha",
};

export const typeOptions = [
  { label: "Aqua", value: "Aqua" },
  { label: "Besta", value: "Beast" },
  { label: "Besta guerreira", value: "Beast-Warrior" },
  { label: "Deus criador", value: "Creator-God" },
  { label: "Ciberso", value: "Cyberse" },
  { label: "Dinossauro", value: "Dinosaur" },
  { label: "Besta divina", value: "Divine-Beast" },
  { label: "Dragão", value: "Dragon" },
  { label: "Fada", value: "Fairy" },
  { label: "Demônio", value: "Fiend" },
  { label: "Peixe", value: "Fish" },
  { label: "Inseto", value: "Insect" },
  { label: "Maquina", value: "Machine" },
  { label: "Planta", value: "Plant" },
  { label: "Psíquico", value: "Psychic" },
  { label: "Piro", value: "Pyro" },
  { label: "Réptio", value: "Reptile" },
  { label: "Rocha", value: "Rock" },
  { label: "Serpente marinha", value: "Sea Serpent" },
  { label: "Mago", value: "Spellcaster" },
  { label: "Trovão", value: "Thunder" },
  { label: "Guerreiro", value: "Warrior" },
  { label: "Besta alada", value: "Winged Beast" },
  { label: "Wyrm", value: "Wyrm" },
  { label: "Zumbi", value: "Zombie" },
];

export const attributeOptions = [
  { value: "DARK", label: "Trevas" },
  { value: "LIGHT", label: "Luz" },
  { value: "FIRE", label: "Fogo" },
  { value: "WATER", label: "Água" },
  { value: "WIND", label: "Vento" },
  { value: "EARTH", label: "Terra" },
  { value: "DIVINE", label: "Divino" },
];

export const categoryOptions = [
  { label: "Normal", value: "normal" },
  { label: "Efeito", value: "effect" },
  { label: "Fusão", value: "fusion" },
  { label: "Ritual", value: "ritual" },
  { label: "Sinchro", value: "synchro" },
  { label: "Xyz", value: "xyz" },
  { label: "Pêndulo", value: "pendulum" },
  { label: "Link", value: "link" },
  { label: "Magia", value: "spell" },
  { label: "Armadilha", value: "trap" },
  { label: "Ficha", value: "token" },
  { label: "Habilidade", value: "skill" },
];

export const levelOptions = [
  { label: "0", value: "0" },
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "9", value: "9" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
];

export const scaleOptions = [
  { label: "0", value: "0" },
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "9", value: "9" },
  { label: "10", value: "10" },
  { label: "11", value: "11" },
  { label: "12", value: "12" },
  { label: "13", value: "13" },
];
