export const cardTypeMap: Record<string, string> = {
    "Effect Monster": "Monstro de efeito",
    "Flip Effect Monster": "Monstro de efeito",
    "Flip Tuner Effect Monster": "Monstro de efeito regulador",
    "Gemini Monster": "Monstro gêmeos",
    "Normal Monster": "Monstro normal",
    "Normal Tuner Monster": "Monstro normal regulador",
    "Pendulum Effect Monster": "Monstro de efeito pêndulo",
    "Pendulum Effect Ritual Monster": "Monstro de efeito pêndulo ritual",
    "Pendulum Flip Effect Monster": "Monstro de efeito pêndulo",
    "Pendulum Normal Monster": "Monstro normal pêndulo",
    "Pendulum Tuner Effect Monster": "Monstro de efeito regulador pêndulo",
    "Ritual Effect Monster": "Monstro de efeito ritual",
    "Ritual Monster": "Monstro ritual",
    "Spell Card": "Carta de magia",
    "Spirit Monster": "Monstro espírito",
    "Toon Monster": "Monstro toon",
    "Trap Card": "Carta de armadilha",
    "Tuner Monster": "Monstro regulador",
    "Union Effect Monster": "Monstro de efeito união",
    "Link Monster": "Monstro link",
    "Fusion Monster": "Monstro fusão",
    "Synchro Monster": "Monstro sincro",
    "Synchro Tuner Monster": "Monstro sincro regulador",
    "XYZ Monster": "Monstro xyz",
    "Skill Card": "Carta de habilidade",
    "Synchro Pendulum Effect Monster": "Monstro de efeito sincro pêndulo",
    "XYZ Pendulum Effect Monster": "Monstro de efeito xyz pêndulo",
    "Pendulum Effect Fusion Monster": "Monstro de efeito fusão pêndulo",
    "Token": "Ficha",
}
